### ISSUE TITLE
Pop up -ikkunoiden luonti ("Palaute tallennettu", "Päivän fiilis tallennettu",...)

### ISSUE THREAD

**Issue by essikipinoinen** [VirpiVuo/HyvinvointiDBWebApp#15]

**Comment by essikipinoinen** [comment]
https://www.aspsnippets.com/Articles/Display-Success-Message-after-Form-Submit-Post-or-Record-Insert-in-ASPNet-MVC.aspx

**Comment by Sonjasusan** [comment]
https://bootswatch.com/cosmo/ <- Saattas toimia helposti noilla alerteillakin
