### ISSUE TITLE
Hymynaama-buttonit

### ISSUE THREAD

**Issue by essikipinoinen** [VirpiVuo/HyvinvointiDBWebApp#3]

**Comment by Sonjasusan** [comment]
Yks vaihtoehto:
https://www.c-sharpcorner.com/forums/how-to-create-button-in-form-from-sql-table-values

Microsoft foorumin esimerkki:
https://forums.asp.net/t/2173892.aspx?how+make+the+button+returns+value+to+database

**Comment by Sonjasusan** [comment]
Tehty.
