### ISSUE TITLE
Dropdownin testaus

### ISSUE THREAD

**Issue by essikipinoinen** [VirpiVuo/HyvinvointiDBWebApp#5]

**Comment by Sonjasusan** [comment]
Sain dropdownin toimimaan (kokeilin tätä  = https://bootswatch.com/cosmo/) 

- Pitää lataa valitsemastaan (tässä cosmo) bootstrap.css & bootstrap.min.css -tiedostot ja tallentaa ne oman projektin content paikkaan ( +nimetä ne erilaisiks (koska sielä on jo "bootstap.css / bootstrap.min.css"-nimiset tiedostot, itse nimesin "bootstrapCosmo.css" & "bootstrapCosmo.min.css" -nimillä)
- Sit pitää lisää_layot.cshtml -sivulla se " @Scripts.Render("~/bundles/bootstrapCosmo")"-kohta ja muokata se nimi siihen (=bootstrapCosmo).
- Sit samalle sivulle (_layout.cs.html) 2kpl scriptiä (joiden avulla se käyttää popper.js (=auttaa toimimaan(?)):  
`<script src="https://bootswatch.com/_vendor/popper.js/dist/umd/popper.min.js"></script>`
 `<script src="https://bootswatch.com/_vendor/bootstrap/dist/js/bootstrap.min.js"></script>`
- Muutokset tähän ScriptBundle muutetaan Bundleksi:
- Ennen: `bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(//"~/Scripts/bootstrap.js")); `

- Jälkeen; `bundles.Add(new Bundle("~/bundles/bootstrap").Include("~/Scripts/bootstrap.js"))`

- Korvataan/kommentoidaan _layout.cs.html `<div class="navbar navbar-inverse navbar-fixed-top">`-alkava koodi - omalla valitsemallaan bootstrap dropdownilla
